[build]
  functions = "netlify/functions"
  command = "npm install"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/webhooks/shopify"
  to = "/.netlify/functions/automation"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
